# Generated by Django 5.2.2 on 2025-06-09 21:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id_manga', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=50)),
                ('fecha_publicacion', models.DateField()),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('E', 'En emisión'), ('F', 'Finalizado')], max_length=1)),
            ],
        ),
    ]
