# Generated by Django 5.2.2 on 2025-06-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaMania', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='introduccion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
