# Generated by Django 5.2.2 on 2025-06-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaMania', '0002_manga_introduccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='image_logo',
            field=models.ImageField(blank=True, null=True, upload_to='mangas/logos/'),
        ),
        migrations.AddField(
            model_name='manga',
            name='image_manga',
            field=models.ImageField(blank=True, null=True, upload_to='mangas/covers/'),
        ),
    ]
