# Generated by Django 5.2.2 on 2025-06-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaMania', '0003_manga_image_logo_manga_image_manga'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sitio', models.CharField(default='MangaMania', max_length=100)),
                ('logo_principal', models.ImageField(blank=True, null=True, upload_to='pagina/logo/')),
                ('imagen_banner', models.ImageField(blank=True, null=True, upload_to='pagina/fondo/')),
            ],
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='autor',
            new_name='autor_manga',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='descripcion',
            new_name='descripcion_manga',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='estado',
            new_name='estado_manga',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='fecha_publicacion',
            new_name='fecha_publicacion_manga',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='introduccion',
            new_name='introduccion_manga',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='titulo',
            new_name='titulo_manga',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='image_logo',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='image_manga',
        ),
        migrations.AddField(
            model_name='manga',
            name='image_portada_anime_manga',
            field=models.ImageField(blank=True, null=True, upload_to='mangas/portadaAnime/'),
        ),
        migrations.AddField(
            model_name='manga',
            name='image_portada_v1_manga',
            field=models.ImageField(blank=True, null=True, upload_to='mangas/portadaV1/'),
        ),
        migrations.AddField(
            model_name='manga',
            name='image_titulo_logo_manga',
            field=models.ImageField(blank=True, null=True, upload_to='mangas/tituloLogo/'),
        ),
    ]
