# Generated by Django 5.2.2 on 2025-06-14 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaMania', '0004_paginainfo_rename_autor_manga_autor_manga_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='image_portada_anime_manga',
            new_name='imagen_portada_anime_manga',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='image_portada_v1_manga',
            new_name='imagen_portada_v1_manga',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='image_titulo_logo_manga',
            new_name='imagen_titulo_logo_manga',
        ),
        migrations.RenameField(
            model_name='paginainfo',
            old_name='imagen_banner',
            new_name='imagen_fondo_principal',
        ),
        migrations.RenameField(
            model_name='paginainfo',
            old_name='logo_principal',
            new_name='imagen_logo_principal',
        ),
        migrations.RenameField(
            model_name='paginainfo',
            old_name='nombre_sitio',
            new_name='nombre_pagina',
        ),
    ]
