# Generated by Django 5.2.2 on 2025-06-14 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaMania', '0005_rename_image_portada_anime_manga_manga_imagen_portada_anime_manga_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaginaInfo',
        ),
    ]
