# Generated by Django 5.2.2 on 2025-06-14 07:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaMania', '0006_delete_paginainfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tomo',
            fields=[
                ('id_tomo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_tomo', models.PositiveIntegerField()),
                ('titulo_tomo', models.CharField(max_length=100)),
                ('descripcion_tomo', models.TextField(blank=True, null=True)),
                ('archivo_pdf', models.FileField(upload_to='tomos/pdfs/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion_tomo', models.DateField(blank=True, null=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomos', to='mangaMania.manga')),
            ],
        ),
    ]
