# Generated by Django 5.2.2 on 2025-06-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaMania', '0007_tomo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tomo',
            options={'ordering': ['manga', 'numero_tomo']},
        ),
    ]
