# Generated by Django 5.2.2 on 2025-06-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaMania', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
